export const ADD_WORKOUT = 'ADD_WORKOUT';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const EDIT_WORKOUT= 'EDIT_WORKOUT';

export const ADD_WORKOUT_TEST = 'ADD_WORKOUT_TEST';
export const DELETE_WORKOUT_TEST = 'DELETE_WORKOUT_TEST';
export const EDIT_WORKOUT_TEST= 'EDIT_WORKOUT_TEST';

export const ADD_WORKOUT_DAY = "ADD_WORKOUT_DAY"
export const EDIT_WORKOUT_DAY = "EDIT_WORKOUT_DAY"
export const DELETE_WORKOUT_DAY = "DELETE_WORKOUT_DAY"