export const ADD_WORKOUT = 'ADD_WORKOUT';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const EDIT_WORKOUT= 'EDIT_WORKOUT';

// VISIBILITY_FILTER
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';